---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: raven
  labels:
    app: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket
        image: ravendvd3232.azurecr.io/socket:latest
        ports:
        - name: socket
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: socket-configmap
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        