---
apiVersion: v1
kind: Service
metadata:
  name: socket-svc
  namespace: raven
spec:
  type: ClusterIP
  selector:
    app: socket
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 9376