---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ingress-resources"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Raven-Livestream/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/argocd-apps/ingress/base

  destination:
    server: https://kubernetes.default.svc
    namespace: 
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
