apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smtp-hpa
  namespace: raven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smtp
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80