---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: raven
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ravendvd3232.azurecr.io/backend:v2
        ports:
        - name: backend
          containerPort: 8000
        envFrom:
          - configMapRef:
              name: backend-configmap
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        