---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: raven
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000   # The port on which the service would be visited
      # targetPort: 8000 # the port in the pod