---
apiVersion: v1
kind: Service
metadata:
  name: sysmon-svc
  namespace: sysmon
spec:
  type: LoadBalancer
  selector:
    app: sysmon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000