---
apiVersion: v1
kind: Service
metadata:
  name: sysmon-svc
  namespace: sysmon
spec:
  type: NodePort
  selector:
    app: sysmon
  ports:
    - protocol: TCP
      port: 5000
      # targetPort: 9376