---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:nobleman97/perizer-app.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Add private here
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"