apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bg-svc-hpa
  namespace: raven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bg-svc
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80